<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>warnings</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\Style\PlayVoice.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Resources\Preset\**" />
    <EmbeddedResource Remove="Resources\Preset\**" />
    <None Remove="Resources\Preset\**" />
    <Page Remove="Resources\Preset\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\SOURCEHANSANSSC-HEAVY-2.OTF" />
    <None Remove="Resources\Fonts\SourceHanSansSC-Light-2.otf" />
    <None Remove="Resources\Fonts\SourceHanSansSC-Medium-2.otf" />
    <None Remove="Resources\Style\PlayVoice.ico" />
    <None Remove="Resources\Style\PlayVoice.png" />
    <None Remove="EULA\**\*.md" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\SOURCEHANSANSSC-HEAVY-2.OTF">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\SourceHanSansSC-Light-2.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Fonts\SourceHanSansSC-Medium-2.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Style\PlayVoice.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Style\PlayVoice.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\Deutsch_德语\PlayVoice-Vereinbarung über das Hochladen nutzergenerierter Inhalte und die Nutzung des Steam-Workshop-Dienstes.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\English_英语\PlayVoice UGC Upload and Steam Workshop Service Agreement.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\Español_西班牙语\PlayVoice Acuerdo de subida de CGU y servicios de Steam Workshop.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\Português (Brasil)_巴西葡萄牙语\PlayVoice Contrato de Envio de CGU e Serviço da Oficina Steam.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\Русский_俄语\PlayVoice Соглашение о загрузке пользовательского контента и использовании сервисов Мастерской Steam.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\日本語_日语\PlayVoice UGCアップロードおよびSteamワークショップサービス契約.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\简体中文_简体中文\PlayVoice UGC 上传与 Steam 创意工坊服务协议.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\繁體中文_繁体中文\PlayVoice UGC 上傳與 Steam 工作坊服務協議.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="EULA\한국어_韩语\PlayVoice UGC 업로드 및 Steam 창작마당 서비스 계약.md">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>..\..\DLL\Facepunch.Steamworks.2.5.2\Release\net6.0\Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Thumbnail.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
